= Git from zero to hero: 3. Nom de l'atelier
:Author: Bastien Bonnet, Alexandre Dergham
:toc:
:numbered: 1

== Pré-requis

. Avoir Git installé

. Récupérer le projet en local

	git clone https://github.com/bastien-bonnet/xke-git-from-zero-to-hero-part-3.git

. Se placer dans le répertoire du projet cloné

	cd xke-git-from-zero-to-hero-part-3

. Pour visualiser l'historique des commits sous forme de graphe compact, nous rajoutons un alias `git l`:

	git config alias.l 'log --graph --oneline --color --decorate --all'
+
N'hésitez pas à utiliser cet alias avant et après chaque commande de l'atelier pour bien visualiser les changements apportés par chaque commande lancée.
+
Pour utiliser l'alias que nous venons de définir (ne fonctionne que pour le projet git dans lequel nous l'avons déclaré) :

	git l

. Définir votre éditeur de texte préféré pour Git (commande à taper dans le terminal dans lequel vous réalisez l'exercice) :

	export EDITOR=nano
+
Remplacez `nano` par l'éditeur de votre choix (vim, emacs, gedit, kate…)


== Introduction
=== Programme de l'atelier

Ceci est le troisième atelier d'une série de trois sur l'utilisation de Git

Les objectifs de cette séance sont d'apprendre à :

* Déterminer le commit qui introduit une régression en utilisant git bisect.
* Appliquer une modification isolée avec la commande cherrypick
* Savoir ce qui se cache derrière la commande git pull
* Etre en mesure de résoudre les problèmes liés à la modification d'une branche distante suite à un git push --force
* Choisir un mode de travail adapté à votre projet (Pull-request, git flow, dictateur&lieutenant)

=== Préambule

== Exercices

=== Localiser un commit qui introduit une régression
Dans cet exercice, nous allons détecter la référence d'un commit qui apporte une "régression".
Pour cela, nous allons utiliser la commande `bisect` de git.
Cette commande nous permet de rechercher un commit par dichotomie en testant des sous-ensembles de commits de plus en plus petits.

* `git checkout master`
* ouvrez le fichier A.txt et constatez que le fichier contient le texte **'Bye Bye!'** (Le comportement souhaité étant de contenir **'Hello world'**).
* `git bisect start` : cette commande initie un contexte de recherche de commit par dichotomie
* `git bisect bad` : cette commande indique que le commit actuel (master) inclus l'anomalie testée.
* `git bisect good ccdd677` : cette commande indique que le commit dont la clé SHA-1 est ccdd677 ne comporte pas l'anomalie testée. A ce moment là, git va vous sélectionner un commit situé exactement au milieu de la serie de commit délimitée par le commit que l'ont a défini comme bon et celui qui est défini comme mauvais.
* ouvrez le fichier A.txt et regardez son contenu.

A partir de là, 2 possibilités s'offrent à vous :

* Le fichier A.txt **est conforme** au comportement recherché dans le commit sélectionné par git : tapez la commande `git bisect good`
* Le fichier A.txt **n'est pas conforme** au comportement recherché : tapez la commande `git bisect bad`

Dans les 2 cas, git redéfinira les bornes de la recherche en fonction de votre réponse et vous proposera un autre commit ainsi qu'une estimation du nombre maximum d'itérations nécessaires pour trouver le commit qui a introduit la régression.

* Recommencez la procédure jusqu'à ce que git vous annonce avoir trouvé le commit incriminé : notez la clé SHA-1 du commit
* quittez le mode bisect en tapant la commande `git bisect stop` : cette commande repositionne le HEAD et l'état du file system à l'état qui a précédé l'entré dans le mode bisect.
* une fois le commit détecté, vous pouvez créer un commit 'inverse' de ce commit pour inverser ses modifications : `git revert xxxxx` où xxxxx est la clé SHA-1 que vous aviez notée.

=== Exercice 2
