= Git from zero to hero: 3 - Commandes avancées
:Author: Bastien Bonnet, Alexandre Dergham
:toc:
:numbered: 1

== Programme de l'atelier

Ceci est le troisième atelier d'une série de trois sur l'utilisation de Git

Les objectifs de cette séance sont d'apprendre à :

* Déterminer le commit qui introduit une régression en utilisant git bisect.
* Appliquer une modification isolée avec la commande cherrypick
* Déplacer une sous-partie d'une branche
* Savoir créer et appliquer un patch
* Etre en mesure de résoudre les problèmes liés à la modification d'une branche distante suite à un git push --force

== Pré-requis

. Avoir Git installé

. Récupérer le projet en local

	git clone https://github.com/bastien-bonnet/xke-git-from-zero-to-hero-part-3.git

. Se placer dans le répertoire du projet cloné

	cd xke-git-from-zero-to-hero-part-3

. Pour visualiser l'historique des commits sous forme de graphe compact, nous rajoutons un alias `git l`:

	git config alias.l 'log --graph --oneline --color --decorate --all'
+
N'hésitez pas à utiliser cet alias avant et après chaque commande de l'atelier pour bien visualiser les changements apportés par chaque commande lancée.
+
Pour utiliser l'alias que nous venons de définir (ne fonctionne que pour le projet git dans lequel nous l'avons déclaré) :

	git l

. Définir votre éditeur de texte préféré pour Git (commande à taper dans le terminal dans lequel vous réalisez l'exercice) :

	export EDITOR=nano
+
Remplacez `nano` par l'éditeur de votre choix (vim, emacs, gedit, kate…)


== Exercices

=== Localiser un commit qui introduit une régression
Dans cet exercice, nous allons détecter la référence d'un commit qui apporte une "régression".
Pour cela, nous allons utiliser la commande `bisect` de git.
Cette commande nous permet de rechercher un commit par dichotomie en testant des sous-ensembles de commits de plus en plus petits.

* `git reset --hard origin/master`
* ouvrez le fichier A.txt et constatez que le fichier contient le texte **'Bye Bye!'** (Le comportement souhaité étant de contenir **'Hello world'**).
* `git bisect start` : cette commande initie un contexte de recherche de commit par dichotomie
* `git bisect bad` : cette commande indique que le commit actuel (master) inclus l'anomalie testée.
* `git bisect good ccdd677` : cette commande indique que le commit dont la clé SHA-1 est ccdd677 ne comporte pas l'anomalie testée. A ce moment là, git va vous sélectionner un commit situé exactement au milieu de la serie de commit délimitée par le commit que l'ont a défini comme bon et celui qui est défini comme mauvais.
* ouvrez le fichier A.txt et regardez son contenu.

À partir de là, 2 possibilités s'offrent à vous :

* Le fichier A.txt **est conforme** au comportement recherché dans le commit sélectionné par git : tapez la commande `git bisect good`
* Le fichier A.txt **n'est pas conforme** au comportement recherché : tapez la commande `git bisect bad`

Dans les 2 cas, git redéfinira les bornes de la recherche en fonction de votre réponse et vous proposera un autre commit ainsi qu'une estimation du nombre maximum d'itérations nécessaires pour trouver le commit qui a introduit la régression.

* Recommencez la procédure jusqu'à ce que git vous annonce avoir trouvé le commit incriminé : notez la clé SHA-1 du commit
* quittez le mode bisect en tapant la commande `git bisect reset` : cette commande repositionne le HEAD et l'état du file system à l'état qui a précédé l'entré dans le mode bisect.
* une fois le commit détecté, vous pourriez (*ne le faites pas* pour être prêts pour l'exercice suivant) créer un commit 'inverse' de ce commit pour inverser ses modifications : `git revert xxxxx` où xxxxx est la clé SHA-1 que vous aviez notée.

=== La même en mieux! Automatiser la recherche du commit
Dans cet exercice, nous allons automatiser la recherche du commit en laissant à un script le soin de tester la validité du fichier A.txt à chaque étape du parcours par dichotomie.
Pour cela, nous avons préparé un script `testMyFile.sh` qui retourne 0 si le fichier contient **'Hello world'**. Sinon, il retourne 1.

* `git reset --hard origin/master`
* `cp ./testMyFile.sh ../.` (Nous copions le script de test hors du répertoire géré par git. Le but étant de ne pas perdre le script pendant le parcours de git bisect.).
* `git bisect start`
* `git bisect bad`
* `git bisect good ccdd677`
* `git bisect run ../testMyFile.sh`
* `git bisect reset` (pour mettre fin au contexte bisect)

A ce moment là, git bisect parcours l'arbre de révision en executant le script à chaque itération. A terme, la commande retourne l'identifiant du commit que nous cherchions.

=== Prélever et appliquer les modifications d'un commit isolé d'une branche à l'autre.
Ici, nous allons nous intéresser au fichier B.txt.
Nous souhaitons appliquer à ce fichier une correction introduite par un commit situé sur une autre branche dans pour autant inclure toutes les modifications apportées par cette branche.
Afin d'y arriver, nous allons utiliser la commande `cherry-pick` qui crée un commit à partir des modifications introduites par un seul commit.

* `git checkout master`
* `git l` : vous constatez la présence d'une branche nommée `cherrypick`. Parmis les commits de cette branche, vous voyez 1 commit `cherry pick me` situé entre 2 commits indésirables.
* `git cherry-pick ddfd83a`
* `git l` : vous voyez l'apparition d'un nouveau commit sur la branche master
* comparez les résultats de `git diff HEAD~2 HEAD` et `git diff 4209c62 ddfd83a`. Vous constaterez que la même modification a été appliquée dans les deux branches.

=== Déplacer une partie d'une branche
Considérons l'état suivant :

----
A---B---C---D master
     \
      E---F---G feature-A
               \
                H---I my-feature
----

Nous avons une branche `my-feature`, créée à partir de `feature-A`, elle-même créée à partir de `master`. Il s’agit d’une erreur, car `my-feature` aurait dû être créée à partir de `master` et ne dépend pas de `feature-A`. Nous voudrions donc déplacer `my-feature` sans ses commits communs avec `feature-A`, c’est-à-dire les commits E, F et G pour la « raccrocher » à `master`. Le résultat voulu serait donc :

----
A---B---C---D master
     \       \
      \       H'---I' my-feature
       \
        E---F---G feature-A
----

Le problème, c'est qu'avec un rebase classique (nous sommes placés sur `my-feature`) :
    
    git rebase master

… nous allons obtenir le résultat suivant :

----
A---B---C---D master
     \       \
      \       E'---F'---G'---H'---I' my-feature
       \
        E---F---G feature-A

----
… car rebase va prendre tous les commmits de `my-feature` n'appartenant pas à `master`.

C'est pourquoi rebase propose une syntaxe différence permettant de spécifier un point de départ pour les commits à « embarquer » dans le rebase : 

    git rebase --onto master feature-A my-feature


Le résultat est le suivant :

----
A---B---C---D master
     \       \
      \       H'---I' my-feature
       \
        E---F---G feature-A
----

Appliquez cette technique avecs les branches `master`, `feature-A` et `my-feature` du dépôt de l'atelier. Vous devez prendre les commits de `my-feature` *sans ceux de feature-A* et les déplacer sur `master`.


=== Créer et appliquer un patch
Git fournit la possibilité de crééer des patchs, c'est-à-dire des fichiers contenant un ensemble de changements à appliquer à du code. Cela peut servir, par exemple, à appliquer des changements déjà versionnés dans un autre dépôt, ou bien à partager des changements avec un collègue en cas de perte de réseau.

Cela se fait en deux temps : création du patch (fichier), puis application du patch.

==== Créer le patch
Nous allons créer un patch contenant les modifications apporté par le dernier commit. Gardez à l'esprit qu'un patch peut contenir les modification d'un ensemble de commits.

Créons le patch :

    git format-patch --stdout master~1..master > my_patch.patch

Pour simuler un dépôt dans un état dans lequel il manque les modifications apportées par le patch que nous venons de créer, nous allons retirer le dernier commit :

    git reset --hard HEAD~1


==== Appliquer le patch
Avant d'appliquer un patch, une bonne pratique est de regarder ce que ce patch va apporter comme modifications :

    git apply --stat my_patch.patch

Une fois cela fait, une autre bonne pratique est de regarder si l'application du patch va causer des problèmes (conflits) :

    git apply --check my_patch.patch

Si rien n'est affiché, il n'y aura pas de problème. Ce devrait être le cas dans cet atelier.

Enfin, nous pouvons donc appliquer réellement le patch :

    git am < my_patch.patch

Cette dernière commande applique le patch et effectue un commit avec son contenu, jusqu'à l'écriture du message de commit.

Vérifier que vous avez bien effectué un nouveau commit avec notre alias :

    git l

== Live... Gitting  (je suppose \^_^°)

=== Mise en situation : J'ai modifié la référence d'une branche distante et mes équipiers perdent les références à cette branche
==== Explication

Vous vous souvenez qu'on vous a dit de ne jamais utiliser la commande rebase sur une branche qui a déjà été persistée sur le dépôt distant ? Voici une situation qui peut avoir lieu si vous ne respectez pas cette bonne pratique.

Soit une branche `bX` déjà poussée sur le dépôt origin et une branche master qui a évolué depuis la création et la persistance de cette branche. Cette branche `bX` prend racine sur la branche `master` au niveau du commit `c0`.

je lance les commandes suivantes : `git checkout bX`, `git rebase master`, `git push origin bX --force`.

Ce faisant, je force mon dépôt distant à déréférencer ma précédente branche `bX` pour en créer une nouvelle qui est issue du dernier commit de la branche `master` `c1`.

Si j'étais seul sur mon projet, cette opération n'aurait eu aucun impact visible parce que ma nouvelle branche distance est correctement référencée et associée à la nouvelle branche sur le dépôt distant...

Malheureusement, je ne suis pas seul et mes équipiers commencent à venir me voir un par un pour me demander pourquoi les commits qu'ils ont rajoutés sur leur branche bX en local n'existent plus depuis qu'ils ont lancé la commande `git pull`...

==== Solution

Avant de proposer une solution, nous allons revenir un moment sur ce qui vient de se passer :

En temps normal, Git ne permet pas de pousser un changement de référence de branche sur un dépôt distant mais l'option `--force` de push permet d'outrepasser cette sécurité. Cette option force Git à déréférencer l'ancienne branche bX distante pour en créer une nouvelle qui va porter cette référence.
Jusque là, tout va bien. Mon dépot local est synchronisé avec le dépôt distant.

Cependant, un de mes équipiers a rajouté un commit sur sa version locale de la branche `bX` et tente de pousser cette modification de la branche sur le dépôt. Celui-ci lui réponds que la branche bX prenant racine en `c0` n'existe plus.
A ce moment là, mon équipier a 2 solutions :

* Forcer à son tour un push sur la branche bX qui aurait pour effet de rétablir la branche qui prend racine en `c0`.
* Récupérer la nouvelle référence de branche à l'aide d'un `git pull` pour y inclures ses modifications locales avant de la pousser sur le dépôt.

Vous l'aurez compris, la première solution (d'un bourrinisme achevé) est à éviter car elle ne résout rien de manière durable puisque je serais à mon tour victime d'une incohérence entre ma branche locale et celle du dépôt.

Nous allons maintenant explorer ensemble la deuxième solution :

* Mon équipier récupère la nouvelle référence de bX: `git pull origin bX`
* La nouvelle référence de bX apparait dans l'arbre de révision local mais la précédente branche locale a disparue avec le commit que l'équipier souhaitait pousser sur le dépôt.
* Dans un premier temps, il faut retrouver la clé du commit à récupérer. Pour cela, nous allons utiliser `git reflog`.
* Une fois cette commande exécutée, on recherche la clé correspondant à ce commit (vraisemblablement juste avant l'execution de `git pull`)
* Maintenant que la clé est retrouvée, il ne reste plus qu'à demander à git de reporter les modification appliquées à ma branche anciennement perdue sur la nouvelle branche. Pour ça, je fais `git checkout <SHA1_perdu>` puis `git rebase bX`
* Dans ce context, va automatiquement détecter que certains commits de l'ancienne branche sont identiques en contenu à des commits de la nouvelle branche. Ainsi, git ne rajoutera dans nouvelle branche `bX` que les commits qui ont été rajoutés dans l'ancienne branche `bX`.

